import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service — Doppel",
  description: "Doppel Terms of Service. Learn how you can use Doppel and what we expect from users.",
};

const SECTIONS = [
  {
    title: "What Doppel Is",
    body: [
      "Doppel is an AI knowledge preservation tool. It lets you capture your thinking, decisions, and communication patterns so they remain accessible — to you, your team, or anyone you choose to share with.",
      "When you or someone else chats with a Doppel clone, they are talking to an AI system trained on that person's data. They are not talking to the real person. Clone responses are generated by a language model and are influenced by — but are not identical to — how the real person thinks or writes.",
      "Doppel is designed to always disclose its AI identity. Clones will not claim to be human when sincerely asked, and the interface makes clear that interactions are with an AI representation.",
    ],
  },
  {
    title: "User Responsibilities",
    body: [
      "You are responsible for the data you bring into Doppel. This includes emails, documents, Slack messages, and any other content you ingest. By ingesting data, you represent that you own that data or have the rights to use it for this purpose, and that if the data includes information about other people, you have a legitimate basis to use it.",
      "You must not use Doppel to harass, deceive, or harm others. You must not create clones of real people without their consent, or use Doppel to impersonate someone for fraudulent purposes.",
    ],
  },
  {
    title: "Acceptable Use",
    body: [
      "Doppel is built for legitimate knowledge management, productivity, and professional use. Acceptable uses include preserving your own institutional knowledge, onboarding new teammates, making your expertise accessible asynchronously, and building a queryable record of your decisions and reasoning.",
      "The following uses are prohibited:",
    ],
    list: [
      "Creating a clone of a real person without their consent in order to deceive others into believing they are interacting with that person.",
      "Using Doppel to generate content for fraud, phishing, spam, or any other deceptive or illegal purpose.",
      "Ingesting data you do not have the right to use — including other people's private communications, confidential company data without authorization, or copyrighted material you do not license.",
      "Using Doppel to build products or services that violate these terms or applicable law.",
    ],
    post: ["We reserve the right to suspend accounts that violate these terms without prior notice."],
  },
  {
    title: "AI-Generated Content Disclaimer",
    body: [
      "All responses generated by Doppel clones are produced by AI language models. They reflect patterns learned from the ingested data, but they are not guaranteed to be accurate, complete, or representative of what the real person would actually say.",
      "AI systems can hallucinate — generating responses that sound confident but are factually wrong. Clone responses may misrepresent the views of the real person, especially on topics not covered by the training data.",
      "Do not rely on Doppel for legal, medical, financial, or safety-critical advice. Do not use clone responses as substitutes for direct communication on matters that require accuracy. Always verify important information through primary sources.",
    ],
  },
  {
    title: "Data Ownership",
    body: [
      "You own your data. Everything you ingest into Doppel — your emails, documents, messages, and Q&A answers — remains yours.",
      "Doppel does not sell your data to third parties. We do not use your data to train shared AI models or improve models for other users. Your data is isolated within your account and your clones.",
      "You can export your data at any time from Settings. You can delete your account and all associated data at any time from Settings → Delete my data. Deletion is permanent and irreversible.",
    ],
  },
  {
    title: "Limitation of Liability",
    body: [
      "To the maximum extent permitted by applicable law, Doppel and its affiliates, officers, employees, and contractors will not be liable for any indirect, incidental, special, consequential, or punitive damages — including loss of profits, data, or goodwill — arising from your use of or inability to use the service.",
      "Our total liability for any claim arising from these terms or your use of Doppel is limited to the amount you paid us in the twelve months preceding the claim, or $100, whichever is greater.",
      "Some jurisdictions do not allow the exclusion of certain warranties or limitations of liability, so parts of this section may not apply to you.",
    ],
  },
  {
    title: "Changes to These Terms",
    body: [
      "We may update these terms from time to time. When we make material changes, we will notify you by email and post the updated terms at doppel.ai/terms with a revised \"Last updated\" date. Your continued use of Doppel after the effective date of the updated terms constitutes acceptance.",
      "If you disagree with any changes, you may close your account at any time from Settings.",
    ],
  },
  {
    title: "Contact",
    body: [
      "If you have questions about these terms or need to report a violation, contact us at legal@doppel.ai. We aim to respond within 3 business days.",
    ],
  },
];

export default function TermsPage() {
  return (
    <div className="doppel-marketing" style={{ fontFamily: "var(--font-sans)" }}>
      {/* Nav */}
      <header className="nav nav--scrolled">
        <div className="nav__inner">
          <Link href="/" className="nav__brand">
            <span className="nav__brand__mark" />
            doppel
          </Link>
          <nav className="nav__links">
            <Link className="nav__link" href="/#pricing">Pricing</Link>
            <Link className="nav__link" href="/contact">Contact</Link>
          </nav>
          <div className="nav__cta-group">
            <Link href="/sign-in" className="btn btn--ghost">Sign in</Link>
            <Link href="/sign-up" className="btn btn--primary">Start free</Link>
          </div>
        </div>
      </header>

      {/* Content */}
      <div className="legal">
        <h1 className="legal__h1">Terms of Service</h1>
        <p className="legal__date">Last updated May 1, 2026</p>

        <p>
          These terms govern your access to and use of Doppel (&ldquo;Doppel&rdquo;, &ldquo;we&rdquo;,
          &ldquo;us&rdquo;). By creating an account or using any part of the service, you agree to these
          terms. Please read them carefully — they explain what Doppel is, what you&rsquo;re responsible
          for, and how we both operate.
        </p>

        {SECTIONS.map((section, i) => (
          <div key={i}>
            <h2>{i + 1}. {section.title}</h2>
            {section.body.map((para, j) => (
              <p key={j}>{para}</p>
            ))}
            {"list" in section && section.list && (
              <ul>
                {section.list.map((item, j) => (
                  <li key={j}>{item}</li>
                ))}
              </ul>
            )}
            {"post" in section && section.post?.map((para, j) => (
              <p key={j}>{para}</p>
            ))}
          </div>
        ))}
      </div>

      {/* Footer */}
      <footer className="foot">
        <div className="foot__inner">
          <div className="foot__brand">doppel</div>
          <span className="foot__legal">&copy; 2026 Doppel AI, Inc.</span>
          <div className="foot__links">
            <Link href="/contact">Contact</Link>
            <a href="/terms">Terms</a>
            <a href="/privacy">Privacy</a>
          </div>
        </div>
      </footer>
    </div>
  );
}
