/* ============================================================================
   Doppel — fixtures (realistic data for the polished surfaces)
   ========================================================================== */

const CLONES = [
  {
    id: "sarah-chen",
    name: "Sarah Chen",
    handle: "sarah",
    role: "VP Engineering · former Stripe",
    cat: "engineering",
    price: 0.50,
    free: false,
    short: "Strategy and architecture trained on six years of engineering decisions and post-mortems.",
    long: "Engineering leader with experience scaling payments infrastructure from 50 to 500 engineers. I'll help you with architecture decisions, technical org design, and the awkward middle ground where systems start breaking.",
    queries: 12438,
    rating: 4.9,
    ratings: 342,
    mem: { episodic: 4204, semantic: 4500, procedural: 2500 },
    verified: true,
    level: "top",
    response: "~2s avg",
    queue: 14,
    sources: [
      { kind: "Slack", count: 8420, label: "internal threads, 2018–2024" },
      { kind: "GitHub", count: 1340, label: "PR reviews + design docs" },
      { kind: "Notion", count: 642, label: "post-mortems, RFCs" },
      { kind: "Email", count: 802, label: "exec correspondence" },
    ],
    tags: ["system design", "tech debt", "hiring"],
    quote: "Most of the bad decisions I see are scaling decisions made too early.",
  },
  {
    id: "amit-rao",
    name: "Amit Rao",
    handle: "amit",
    role: "Staff Eng · debugging deep",
    cat: "engineering",
    price: 0,
    free: true,
    short: "Debugging, system design, code review — patterns from real PR threads.",
    long: "I spend my time in production code. Give me a stack trace, a flaky test, or a system you're trying to understand. I'll walk through it the way I'd review a junior's PR.",
    queries: 8205,
    rating: 4.8,
    ratings: 128,
    mem: { episodic: 3402, semantic: 2000, procedural: 2000 },
    verified: true,
    level: "lvl2",
    response: "~3s avg",
    queue: 6,
    sources: [
      { kind: "GitHub", count: 5200, label: "10 years of PR threads" },
      { kind: "Slack", count: 1800, label: "incident channels" },
      { kind: "Notion", count: 402, label: "personal debugging notes" },
    ],
    tags: ["debugging", "code review"],
    quote: "Read the error twice. The answer is usually in the first line.",
  },
  {
    id: "maya-lee",
    name: "Maya Lee",
    handle: "maya",
    role: "Design lead · former Figma",
    cat: "design",
    price: 0.25,
    free: false,
    short: "Product design critique drawn from 700 portfolio reviews and design-engineering escalations.",
    long: "I review portfolios. I write design docs. I tell designers when their thing is too clever. Bring me a screen, a flow, or a stuck feeling — I'll respond like I'd write it in Slack.",
    queries: 1842,
    rating: 4.7,
    ratings: 86,
    mem: { episodic: 1620, semantic: 800, procedural: 700 },
    verified: false,
    level: "lvl2",
    response: "~3s avg",
    queue: 3,
    sources: [
      { kind: "Figma", count: 720, label: "design-review comments" },
      { kind: "Slack", count: 980, label: "design-eng threads" },
      { kind: "Notion", count: 240, label: "portfolio reviews" },
    ],
    tags: ["product design", "critique"],
    quote: "If two designers can't agree on it, neither has met the user.",
  },
  {
    id: "reza-karim",
    name: "Reza Karim",
    handle: "reza",
    role: "CMO · 3 exits",
    cat: "marketing",
    price: 0.40,
    free: false,
    short: "Positioning, GTM, brand. Series B to IPO playbooks from three exits.",
    long: "Marketing operator. I've launched products at every stage from pre-seed to post-IPO. I'm sharper on positioning than on demand-gen, and I'll tell you when you're skipping the work.",
    queries: 6920,
    rating: 4.9,
    ratings: 211,
    mem: { episodic: 2900, semantic: 1500, procedural: 1000 },
    verified: true,
    level: "lvl2",
    response: "~2s avg",
    queue: 9,
    sources: [
      { kind: "Notion", count: 1200, label: "launch playbooks" },
      { kind: "Email", count: 2400, label: "team correspondence" },
      { kind: "Slack", count: 800, label: "GTM threads" },
    ],
    tags: ["positioning", "GTM"],
    quote: "If you can't say it in a sentence, the market won't hear it.",
  },
  {
    id: "jia-park",
    name: "Jia Park",
    handle: "jia",
    role: "Fractional CFO",
    cat: "finance",
    price: 1.00,
    free: false,
    short: "CFO advisor. Cap table, runway, board prep for first-time founders.",
    long: "Fractional CFO working with 12 active startups. I'll model your runway, sanity-check your cap table, and prep your board deck. Direct, numbers-first, no fluff.",
    queries: 540,
    rating: 5.0,
    ratings: 64,
    mem: { episodic: 1400, semantic: 600, procedural: 210 },
    verified: true,
    level: "lvl1",
    response: "~4s avg",
    queue: 2,
    sources: [
      { kind: "Sheets", count: 240, label: "client financial models" },
      { kind: "Notion", count: 180, label: "board memos" },
      { kind: "Email", count: 660, label: "investor correspondence" },
    ],
    tags: ["fundraising", "runway"],
    quote: "Show me the next 18 months. Then we'll talk about strategy.",
  },
  {
    id: "tom-vance",
    name: "Tom Vance",
    handle: "tom",
    role: "Operator · 3× SaaS to $50M+",
    cat: "business",
    price: 0.30,
    free: false,
    short: "Operator notes from scaling three SaaS companies past $50M ARR.",
    long: "I've scaled three companies from product-market fit through the messy middle. Ask me about org design, hiring at the wrong moment, killing a product line. I'll say things that won't make it into a podcast.",
    queries: 4080,
    rating: 4.6,
    ratings: 154,
    mem: { episodic: 3800, semantic: 1500, procedural: 980 },
    verified: false,
    level: "lvl2",
    response: "~3s avg",
    queue: 5,
    sources: [
      { kind: "Notion", count: 800, label: "operating principles" },
      { kind: "Slack", count: 3200, label: "leadership threads" },
      { kind: "Email", count: 1800, label: "exec correspondence" },
    ],
    tags: ["operating", "scaling"],
    quote: "The hardest year is the one after product-market fit.",
  },
  {
    id: "lin-wei",
    name: "Lin Wei",
    handle: "lin",
    role: "Clinical operations",
    cat: "healthcare",
    price: 0,
    free: true,
    short: "Clinical operations playbook. Triage, staffing, EHR pitfalls.",
    long: "Operations director at a 200-bed hospital. I'll talk through staffing models, EHR rollouts, and what no one writes down about clinical workflow.",
    queries: 312,
    rating: 4.5,
    ratings: 39,
    mem: { episodic: 980, semantic: 600, procedural: 240 },
    verified: false,
    level: "lvl1",
    response: "~5s avg",
    queue: 1,
    sources: [
      { kind: "Notion", count: 240, label: "ops playbooks" },
      { kind: "Email", count: 1300, label: "rounds correspondence" },
    ],
    tags: ["ops", "EHR"],
    quote: "The system breaks at handoff, every time.",
  },
  {
    id: "eli-brooks",
    name: "Eli Brooks",
    handle: "eli",
    role: "Grad-CS teaching faculty",
    cat: "education",
    price: 0.20,
    free: false,
    short: "Curriculum design and tutoring frameworks. Eight years teaching grad CS.",
    long: "I teach graduate-level CS. I'll help you design a curriculum, structure office hours, or work through a concept that isn't clicking. I prefer Socratic.",
    queries: 1612,
    rating: 4.8,
    ratings: 92,
    mem: { episodic: 1840, semantic: 700, procedural: 300 },
    verified: true,
    level: "lvl1",
    response: "~3s avg",
    queue: 4,
    sources: [
      { kind: "Notion", count: 320, label: "lecture notes" },
      { kind: "Email", count: 1100, label: "student threads" },
      { kind: "GitHub", count: 220, label: "assignment templates" },
    ],
    tags: ["curriculum", "tutoring"],
    quote: "The way you ask the question is half the answer.",
  },
];

/* Category counts derived from fixtures */
const CAT_COUNTS = {};
catKeys.forEach((k) => { CAT_COUNTS[k] = CLONES.filter((c) => c.cat === k).length; });

/* Sample questions per category (replaces hard-coded list) */
const SAMPLE_QS = {
  engineering: [
    "How do you decide when to pay down tech debt vs ship?",
    "What's your process when on-call burns out the team?",
    "When do you reach for a monorepo vs split repos?",
  ],
  design: [
    "How do you handle design and engineering disagreement?",
    "What's your test for whether a design is done?",
    "How do you frame a portfolio review for someone early career?",
  ],
  business: [
    "How do you know it's time to kill a product line?",
    "What's your framework for the messy middle after PMF?",
    "When do you hire ahead of revenue vs after?",
  ],
  marketing: [
    "How do you sharpen positioning that's gotten fuzzy?",
    "What's your GTM checklist before a launch?",
    "When does brand-building start to matter vs distract?",
  ],
  finance: [
    "How do I build a runway model for the next 18 months?",
    "What metrics should I show at my next board meeting?",
    "How do you think about burn vs growth at seed?",
  ],
  healthcare: [
    "How do you staff a 24/7 clinical floor without burnout?",
    "Where do EHR rollouts typically fail?",
    "What's your triage framework for a sudden surge?",
  ],
  education: [
    "How do you design office hours that actually help?",
    "What's your approach when a student isn't engaging?",
    "How do you sequence prerequisites for a hard course?",
  ],
};

/* Reviews fixture (per clone) — varied tones */
const REVIEWS_FOR = (handle) => [
  { name: "Avery K.", initial: "A", color: "#1A73E8", rating: 5, date: "2 weeks ago",
    text: "Asked her about whether to refactor the payments service or rewrite. Got a clear framework in under a minute. Cited the actual post-mortem from her old team. Worth the credit." },
  { name: "Jordan M.", initial: "J", color: "#7B1FA2", rating: 5, date: "1 month ago",
    text: "I keep coming back. The answers are short, direct, and they sound like her — I've heard her talk before. Confidence scores have been accurate.",
    reply: "Glad it lands. The one thing I'd add: the model is best on architecture and team-design questions. Cap-table specifics still belong to a human." },
  { name: "Priya S.", initial: "P", color: "#2E7D32", rating: 4, date: "1 month ago",
    text: "Helpful for high-level direction. Wished it would push back more when I described a bad idea — sometimes I want the disagreement." },
  { name: "Ben C.", initial: "B", color: "#F57C00", rating: 5, date: "2 months ago",
    text: "Used this in prep for a board meeting. Saved me an afternoon of writing the memo myself." },
];

Object.assign(window, { CLONES, CAT_COUNTS, SAMPLE_QS, REVIEWS_FOR });
